# Generated by Django 2.2.6 on 2019-10-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191014_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='cours',
            name='Eleves',
            field=models.ManyToManyField(related_name='cours', to='polls.Eleve'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
