# Generated by Django 2.2.6 on 2019-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191014_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Eleves',
            field=models.ManyToManyField(related_name='Cours', to='polls.Eleve'),
        ),
    ]
