# Generated by Django 2.2.6 on 2019-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191014_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cours', models.CharField(max_length=200)),
                ('Année', models.DateField()),
                ('Eleves', models.ManyToManyField(related_name='Cour', to='polls.Eleve')),
            ],
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
    ]
