# Generated by Django 2.2.6 on 2019-10-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191014_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_prof', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='Title_of_the_project',
            field=models.CharField(default='', max_length=200),
        ),
    ]
